-- AlterTable
ALTER TABLE "Course" ALTER COLUMN "human_weight" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "language_weight" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "math_weight" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "nature_weight" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "redacao_weight" SET DATA TYPE DOUBLE PRECISION;
